# Generated by Django 5.2.5 on 2025-09-14 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('contact', models.CharField(max_length=12)),
                ('department', models.CharField(max_length=50)),
                ('register_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('roll_no', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=12)),
                ('department', models.CharField(max_length=50)),
                ('register_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('project_url', models.URLField()),
                ('status', models.CharField(default='pending')),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=150)),
                ('issue_date', models.DateField()),
                ('document', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('status', models.CharField(default='pending')),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('activity_type', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('project_url', models.URLField()),
                ('status', models.CharField(default='pending')),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='email')),
            ],
        ),
    ]
