# Generated by Django 5.2.5 on 2025-09-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificate',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
