# Generated by Django 5.2.5 on 2025-09-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_faculty_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='branch',
        ),
        migrations.AddField(
            model_name='faculty',
            name='College_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='College_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
