# Generated by Django 5.2.5 on 2025-09-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_department_student_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='faculty',
            name='gender',
            field=models.CharField(default='unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
