# Generated by Django 5.2.5 on 2025-09-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_name_faculty_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
