# Generated by Django 5.2.5 on 2025-09-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_activities_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(default='B.Tech', max_length=100),
            preserve_default=False,
        ),
    ]
