# Generated by Django 5.2.5 on 2025-09-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='remark',
            field=models.TextField(default='None', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='remark',
            field=models.TextField(default='None', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='remark',
            field=models.TextField(default='None', max_length=500),
            preserve_default=False,
        ),
    ]
