# Generated by Django 5.2.5 on 2025-09-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_activities_remark_certificate_remark_projects_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='linked_in',
            field=models.URLField(blank=True, null=True),
        ),
    ]
