# Generated by Django 5.2.5 on 2025-09-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_student_github_student_linked_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='github',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='linked_in',
            new_name='linkedin_url',
        ),
    ]
