# Generated by Django 5.2.5 on 2025-09-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_subject_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
