# Generated by Django 5.2.5 on 2025-09-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_activities_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='student_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='student.student', verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='student.student', verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='student_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='student.student', verbose_name='email'),
        ),
    ]
